import { spawn } from 'node:child_process'
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'

const chrome = 'C:/Program Files/Google/Chrome/Application/chrome.exe'
const profile = await mkdtemp(path.join(tmpdir(), 'camy-browser-smoke-'))
const browser = spawn(chrome, ['--headless=new', '--disable-gpu', '--no-sandbox', '--no-first-run', '--no-default-browser-check', '--remote-debugging-pipe', `--user-data-dir=${profile}`, 'about:blank'], { windowsHide: true, stdio: ['ignore','ignore','ignore','pipe','pipe'] })
let sessionId, next = 0
const pending = new Map(), errors = []
let buffer = ''
browser.stdio[4].on('data', chunk => {
  buffer += chunk.toString()
  let boundary
  while((boundary=buffer.indexOf('\0')) >= 0){
    const frame=buffer.slice(0,boundary);buffer=buffer.slice(boundary+1);if(!frame)continue
    const message=JSON.parse(frame)
    if(message.id && pending.has(message.id)){
      const task=pending.get(message.id);pending.delete(message.id)
      if(message.error)task.reject(Error(message.error.message));else task.resolve(message.result)
    }
    if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails.exception?.description||message.params.exceptionDetails.text)
  }
})
const pause = ms => new Promise(resolve => setTimeout(resolve, ms))
const send = (method, params = {}) => new Promise((resolve, reject) => {
  const id = ++next
  const timeout = setTimeout(() => { pending.delete(id); reject(Error(`Timeout: ${method}`)) }, 15000)
  pending.set(id, { resolve: value => { clearTimeout(timeout); resolve(value) }, reject })
  browser.stdio[3].write(JSON.stringify({ id, method, params, ...(sessionId&&!method.startsWith('Browser.')&&!method.startsWith('Target.')?{sessionId}:{}) })+'\0')
})
const evaluate = async expression => {
  const result = await send('Runtime.evaluate', { expression, awaitPromise: true, returnByValue: true })
  if (result.exceptionDetails) throw Error(result.exceptionDetails.text + ': ' + (result.exceptionDetails.exception?.description || ''))
  return result.result.value
}
const check = (condition, message) => { if (!condition) throw Error(message) }
try {
  const target=await send('Target.createTarget',{url:'about:blank'})
  sessionId=(await send('Target.attachToTarget',{targetId:target.targetId,flatten:true})).sessionId
  await send('Runtime.enable'); await send('Page.enable')
  await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
  await send('Page.navigate', { url: 'http://127.0.0.1:8080/' })
  for (let attempt = 0; attempt < 60; attempt++) {
    if (await evaluate("document.body.innerText.includes('Sign in to your account')")) break
    await pause(100)
  }
  check(await evaluate("document.body.innerText.includes('Sign in to your account')"), 'Login screen did not load')
  await mkdir('private/review', { recursive: true })
  await send('Page.navigate', { url: 'http://127.0.0.1:8080/shops' })
  for(let attempt=0;attempt<60;attempt++){if(await evaluate("!!document.querySelector('.shop-hero')"))break;await pause(100)}
  await pause(300)
  check(await evaluate("document.querySelector('.shop-hero') && getComputedStyle(document.querySelector('.shop-hero')).backgroundImage.includes('linear-gradient') && getComputedStyle(document.querySelector('.shop-hero h1')).color==='rgb(255, 255, 255)'"), 'Real customer route is missing its dark-blue theme')
  check(await evaluate("document.querySelector('.shop-logo img').src.includes('camylogo') && document.querySelector('.shop-logo img').naturalWidth===554"), 'Real shop is not using the uploaded CAMY logo')
  check(await evaluate("getComputedStyle(document.querySelector('.shop-hero-visual img')).mixBlendMode==='normal' && getComputedStyle(document.querySelector('.shop-header')).backdropFilter==='none'"), 'Customer page still uses image blending or backdrop effects')
  const realShop=await send('Page.captureScreenshot',{format:'png'})
  await writeFile('private/review/customer-live-desktop.png',Buffer.from(realShop.data,'base64'))
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await pause(120)
  check(await evaluate("document.documentElement.scrollWidth<=innerWidth && getComputedStyle(document.querySelector('.shop-hero')).gridTemplateColumns.split(' ').length===1"), 'Real mobile shop CSS or viewport layout is broken')
  const realMobile=await send('Page.captureScreenshot',{format:'png'})
  await writeFile('private/review/customer-live-mobile.png',Buffer.from(realMobile.data,'base64'))
  await send('Emulation.setDeviceMetricsOverride', { width: 1280, height: 900, deviceScaleFactor: 1, mobile: false })
  await send('Page.navigate', { url: 'http://127.0.0.1:8080/' })
  for(let attempt=0;attempt<60;attempt++){if(await evaluate("document.body.innerText.includes('Sign in to your account')"))break;await pause(100)}
  // UI fixtures do not create or modify production accounts or orders.
  await evaluate("import('/scripts/browser-fixture.jsx').then(module=>module.mountFixture())")
  await pause(400)
  await evaluate("window.scrollTo(0,400);[...document.querySelectorAll('button')].find(button=>button.textContent.includes('View full request')).click()")
  await pause(150)
  let details = await evaluate("(()=>{const dialog=document.querySelector('.supply-detail');const rect=dialog.getBoundingClientRect();return {top:rect.top,bottom:rect.bottom,height:innerHeight,overflow:document.body.style.overflow,text:dialog.innerText}})()")
  check(details.top >= 0 && details.bottom <= details.height + 1, 'Request dialog escaped desktop viewport')
  check(details.overflow === 'hidden' && details.text.includes('Test delivery address'), 'Dialog lock or contact details missing')
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape' }); await pause(100)
  check(await evaluate("!document.querySelector('.supply-detail') && document.activeElement.textContent.includes('View full request')"), 'Escape did not close dialog and restore focus')
  await evaluate("[...document.querySelectorAll('button')].find(button=>button.textContent.includes('View full request')).click()")
  await pause(100)
  await evaluate("[...document.querySelectorAll('button')].find(button=>button.textContent.includes('Edit quantities')).click()")
  await pause(100)
  check(await evaluate("!!document.querySelector('.supply-edit-row input')"), 'Pending request editor missing')
  await evaluate("[...document.querySelectorAll('button')].find(button=>button.textContent==='Cancel editing').click();[...document.querySelectorAll('button')].find(button=>button.textContent==='Accept request').click()")
  await pause(150)
  check(await evaluate("document.querySelector('.supply-detail').innerText.includes('Reject / cancel request')"), 'Accepted request did not show cancellation action')
  await mkdir('private/review', { recursive: true })
  const desktop = await send('Page.captureScreenshot', { format: 'png' })
  await writeFile('private/review/stock-request-desktop.png', Buffer.from(desktop.data, 'base64'))
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await pause(150)
  details = await evaluate("(()=>{const rect=document.querySelector('.supply-detail').getBoundingClientRect();return {top:rect.top,bottom:rect.bottom,left:rect.left,right:rect.right,width:innerWidth,height:innerHeight}})()")
  check(details.top >= 0 && details.bottom <= details.height + 1 && details.left >= 0 && details.right <= details.width + 1, 'Request dialog escaped mobile viewport')
  const mobile = await send('Page.captureScreenshot', { format: 'png' })
  await writeFile('private/review/stock-request-mobile.png', Buffer.from(mobile.data, 'base64'))
  await send('Emulation.setDeviceMetricsOverride', { width: 1440, height: 1000, deviceScaleFactor: 1, mobile: false })
  await evaluate("import('/scripts/browser-fixture.jsx').then(module=>module.mountShopFixture())")
  await pause(450)
  await evaluate("window.scrollTo(0,0)")
  await evaluate("window.setUiField=(selector,value)=>{const field=document.querySelector(selector);const type=field.tagName==='SELECT'?HTMLSelectElement:field.tagName==='TEXTAREA'?HTMLTextAreaElement:HTMLInputElement;Object.getOwnPropertyDescriptor(type.prototype,'value').set.call(field,value);field.dispatchEvent(new Event(field.tagName==='SELECT'?'change':'input',{bubbles:true}))}")
  check(await evaluate("document.querySelectorAll('.shop-product-card').length===4"), 'Shop collection did not load')
  await evaluate("document.querySelector('.shop-favourite').click()")
  await pause(130)
  check(await evaluate("document.querySelector('.shop-favourite').getAttribute('aria-pressed')==='true'"), 'Customer favourite did not persist')
  await evaluate("window.setUiField('[aria-label=\"Minimum product price\"]','5000')")
  await pause(100)
  check(await evaluate("document.querySelectorAll('.shop-product-card').length===3"), 'Product price filter failed')
  await evaluate("window.setUiField('[aria-label=\"Minimum product price\"]','');[...document.querySelectorAll('.shop-categories button')].find(button=>button.textContent==='Kitchen essentials').click()")
  await pause(100)
  check(await evaluate("document.querySelectorAll('.shop-product-card').length===1 && document.querySelector('.shop-product-title').textContent==='Family Casserole'"), 'Category product filter failed')
  await evaluate("document.querySelector('.shop-categories button').click()")
  await pause(80)
  check(await evaluate("document.documentElement.scrollWidth<=innerWidth"), 'Desktop shop has horizontal overflow')
  const shopDesktop = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true })
  await writeFile('private/review/customer-shop-desktop.png', Buffer.from(shopDesktop.data, 'base64'))
  await evaluate("document.querySelector('.shop-product-image').focus();document.querySelector('.shop-product-image').click()")
  await pause(120)
  check(await evaluate("!!document.querySelector('.shop-product-dialog') && !document.querySelector('.shop-product-image svg')"), 'Touch product details or removal of eye icon failed')
  await evaluate("document.querySelector('[aria-label=\"Zoom in\"]').click()")
  await pause(80)
  check(await evaluate("document.querySelector('.shop-zoom-controls').innerText.includes('150%') && document.querySelector('.shop-image-stage').style.width==='150%'"), 'Product zoom in failed')
  await evaluate("document.querySelector('[aria-label=\"Zoom out\"]').click()")
  await pause(80)
  check(await evaluate("document.querySelector('.shop-zoom-controls').innerText.includes('100%')"), 'Product zoom out failed')
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape' }); await pause(100)
  check(await evaluate("!document.querySelector('.shop-product-dialog') && document.activeElement.className==='shop-product-image'"), 'Product dialog Escape/focus failed')
  await evaluate("document.querySelectorAll('.shop-add')[0].click();document.querySelectorAll('.shop-add')[2].click()")
  await pause(120)
  check(await evaluate("document.querySelectorAll('.shop-cart-group').length===2 && document.querySelector('.shop-split-note').innerText.includes('separate receipt')"), 'Mixed-shop cart groups or explanation missing')
  await evaluate("document.querySelector('.shop-checkout .shop-primary').click()")
  await pause(250)
  check(await evaluate("window.shopFixtureOrders.length===2 && !!document.querySelector('.shop-checkout .shop-alert')"), 'Lost-response fixture did not retain checkout for retry')
  await evaluate("document.querySelector('.shop-checkout .shop-primary').click()")
  await pause(250)
  check(await evaluate("window.shopFixtureOrders.length===2 && document.querySelectorAll('.shop-order-card').length===2 && !document.querySelector('.shop-cart')"), 'Retry duplicated orders or failed to navigate to My orders')
  check(await evaluate("!document.querySelector('.bank-details')"), 'Bank details shown before shop approval')
  await evaluate("window.approveShopFixtureOrders();document.querySelectorAll('.shop-order-card').forEach(card=>card.open=true);document.querySelectorAll('.shop-order-body .shop-secondary').forEach(button=>button.click())")
  await pause(200)
  check(await evaluate("document.querySelectorAll('.bank-details').length===2 && document.querySelectorAll('.shop-order-card')[0].innerText.includes('111111') && document.querySelectorAll('.shop-order-card')[1].innerText.includes('222222')"), 'Independent shop banks missing after approvals')
  const testReceipt=path.resolve('private/review/customer-ui-receipt.pdf')
  await writeFile(testReceipt, '%PDF-1.4\nUI test receipt')
  const documentRoot=await send('DOM.getDocument')
  const receiptInput=await send('DOM.querySelector',{nodeId:documentRoot.root.nodeId,selector:'.shop-order-card input[type="file"]'})
  await send('DOM.setFileInputFiles',{nodeId:receiptInput.nodeId,files:[testReceipt]})
  await pause(80)
  await evaluate("document.querySelector('.shop-order-card .workflow-panel .market-primary').click()")
  await pause(180)
  check(await evaluate("window.shopFixtureOrders[0].status==='Payment review' && window.shopFixtureOrders[1].status==='Awaiting payment' && document.querySelectorAll('.shop-order-card')[0].innerText.includes('View submitted receipt')"), 'Receipt upload crossed shop orders or failed to update the UI')
  await rm(testReceipt)
  await evaluate("document.querySelector('.shop-order-card .receipt-view-button').click()")
  await pause(250)
  check(await evaluate("!!document.querySelector('.receipt-preview-content img') && document.querySelector('.receipt-preview-content img').naturalWidth>0"), 'Receipt did not display in the preview without downloading')
  check(await evaluate("(()=>{const rect=document.querySelector('.receipt-preview-dialog').getBoundingClientRect();return rect.top>=0 && rect.bottom<=innerHeight+1})()"), 'Receipt preview escaped desktop viewport')
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape' });await pause(80)
  await evaluate("[...document.querySelectorAll('.customer-account-tabs button')].find(button=>button.textContent==='Purchase history').click()")
  await pause(120)
  check(await evaluate("document.querySelectorAll('.account-purchase').length===2 && document.querySelectorAll('.account-purchase-images img').length===2"), 'Purchased item history/images missing')
  await evaluate("window.setUiField('.account-filter-grid select','Payment review')")
  await pause(100)
  check(await evaluate("document.querySelectorAll('.account-purchase').length===1"), 'Purchase status filter failed')
  await evaluate("document.querySelector('.account-order-filters footer button').click();[...document.querySelectorAll('.customer-account-tabs button')].find(button=>button.textContent==='Overview').click()")
  await pause(100)
  check(await evaluate("document.querySelectorAll('.account-metrics button').length===4 && document.querySelector('.account-recent-order').innerText.includes('Classic Cookware')"), 'Account dashboard or recent items missing')
  const dashboard=await send('Page.captureScreenshot',{format:'png'})
  await writeFile('private/review/customer-account-desktop.png',Buffer.from(dashboard.data,'base64'))
  await evaluate("[...document.querySelectorAll('.customer-account-tabs button')].find(button=>button.textContent==='Address book').click()")
  await pause(100)
  await evaluate("[...document.querySelectorAll('.account-panel header button')].find(button=>button.textContent==='Add address').click()")
  await pause(80)
  await evaluate("window.setUiField('.address-editor input','Office');window.setUiField('.address-editor textarea','456 Test office street');document.querySelector('.address-editor .shop-primary').click()")
  await pause(120)
  check(await evaluate("document.querySelectorAll('.address-book-grid article').length===2 && document.querySelector('.address-book-grid').innerText.includes('Office')"), 'Saved address book failed')
  await evaluate("[...document.querySelectorAll('.customer-account-tabs button')].find(button=>button.textContent==='Saved products').click()")
  await pause(100)
  check(await evaluate("document.querySelectorAll('.shop-product-card').length===1 && document.querySelector('.shop-product-title').innerText.includes('Classic Cookware')"), 'Saved products page missing')
  await evaluate("[...document.querySelectorAll('.shop-header nav button')].find(button=>button.innerText.includes('Explore shops')).click()")
  await pause(100)
  const ordersDesktop = await send('Page.captureScreenshot', { format: 'png' })
  await writeFile('private/review/customer-orders-desktop.png', Buffer.from(ordersDesktop.data, 'base64'))
  await send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 1, mobile: true })
  await pause(100)
  check(await evaluate("document.documentElement.scrollWidth<=innerWidth"), 'Mobile order page has horizontal overflow')
  await evaluate("[...document.querySelectorAll('.shop-header nav button')].find(button=>button.innerText.includes('Explore shops')).click();window.scrollTo(0,0)")
  await pause(150)
  check(await evaluate("document.documentElement.scrollWidth<=innerWidth"), 'Mobile shop has horizontal overflow')
  const shopMobile = await send('Page.captureScreenshot', { format: 'png', captureBeyondViewport: true })
  await writeFile('private/review/customer-shop-mobile.png', Buffer.from(shopMobile.data, 'base64'))
  await evaluate("document.querySelector('.shop-product-image').click()")
  await pause(100)
  check(await evaluate("(()=>{const rect=document.querySelector('.shop-product-dialog').getBoundingClientRect();return rect.left>=0 && rect.right<=innerWidth+1 && rect.top>=0 && rect.bottom<=innerHeight+1})()"), 'Mobile product dialog escaped viewport')
  await send('Input.dispatchKeyEvent', { type: 'keyDown', key: 'Escape', code: 'Escape' });await pause(80)
  await evaluate("window.deliverShopFixtureOrders();[...document.querySelectorAll('.shop-header nav button')].find(button=>button.textContent.includes('My account')).click()")
  await pause(80)
  await evaluate("[...document.querySelectorAll('.customer-account-tabs button')].find(button=>button.textContent==='Purchase history').click()")
  await pause(80)
  await evaluate("document.querySelector('.shop-orders>.shop-section-heading button').click();document.querySelectorAll('.shop-order-card').forEach(card=>card.open=true);document.querySelectorAll('.shop-order-body>.shop-secondary').forEach(button=>button.click())")
  await pause(140)
  check(await evaluate("document.querySelectorAll('.purchase-review').length===2"), 'Delivered purchase review controls missing')
  await evaluate("document.querySelector('.purchase-review .shop-secondary').click()")
  await pause(80)
  await evaluate("window.setUiField('.purchase-review textarea','A very useful cookware collection, delivered safely.');document.querySelector('.purchase-review form .shop-primary').click()")
  await pause(140)
  check(await evaluate("window.shopFixtureReviews.length===1 && document.querySelector('.purchase-review').innerText.includes('Pending')"), 'Customer rating/comment submission failed')
  check(await evaluate("document.documentElement.scrollWidth<=innerWidth"), 'Mobile purchase history has horizontal overflow')
  const historyMobile=await send('Page.captureScreenshot',{format:'png'})
  await writeFile('private/review/customer-history-mobile.png',Buffer.from(historyMobile.data,'base64'))
  await evaluate("import('/scripts/browser-fixture.jsx').then(module=>module.mountFeedbackAdminFixture())")
  await pause(140)
  check(await evaluate("document.querySelector('.admin-feedback-card').innerText.includes('delivered safely')"), 'Admin cannot view customer feedback')
  await evaluate("window.setUiField('.admin-feedback-card textarea','Thank you for supporting a CAMY entrepreneur.');document.querySelector('.admin-feedback-card footer button').click()")
  await pause(140)
  check(await evaluate("window.shopFixtureReviews[0].status==='Published' && document.querySelector('.admin-feedback-card').innerText.includes('Published')"), 'Admin review publishing/reply failed')
  await evaluate("import('/scripts/browser-fixture.jsx').then(module=>module.mountDispatchFixture())")
  await pause(150)
  check(await evaluate("[...document.querySelectorAll('button')].find(button=>button.textContent==='Dispatch order').disabled"), 'Dispatch enabled without a tracking number')
  await evaluate("(()=>{const fields=document.querySelectorAll('.dispatch-fields input');const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;setter.call(fields[0],'Test Courier');fields[0].dispatchEvent(new Event('input',{bubbles:true}));setter.call(fields[1],'TRACK-UI-123');fields[1].dispatchEvent(new Event('input',{bubbles:true}))})()")
  await pause(100)
  await evaluate("[...document.querySelectorAll('button')].find(button=>button.textContent==='Dispatch order').click()")
  await pause(150)
  check(await evaluate("document.body.innerText.includes('Dispatched') && document.body.innerText.includes('TRACK-UI-123') && window.shopFixtureOrders[0].trackingNumber==='TRACK-UI-123'"), 'Dispatch did not save/display tracking number')
  await evaluate("document.querySelector('.receipt-view-button').click()")
  await pause(200)
  check(await evaluate("(()=>{const rect=document.querySelector('.receipt-preview-dialog').getBoundingClientRect();return rect.top>=0&&rect.bottom<=innerHeight+1&&rect.left>=0&&rect.right<=innerWidth+1})()"), 'Receipt preview escaped mobile viewport')
  await evaluate("import('/scripts/browser-fixture.jsx').then(module=>module.mountReturnFixture())")
  await pause(150)
  const clickButton = async text => { await evaluate('[...document.querySelectorAll("button")].find(button=>button.textContent==='+JSON.stringify(text)+').click()'); await pause(120) }
  const fillField = async (selector,value) => { await evaluate('(()=>{const field=document.querySelector('+JSON.stringify(selector)+');const setter=Object.getOwnPropertyDescriptor(field.tagName==="TEXTAREA"?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,"value").set;setter.call(field,'+JSON.stringify(value)+');field.dispatchEvent(new Event("input",{bubbles:true}))})()'); await pause(60) }
  check(await evaluate('document.querySelector(".order-return-panel button").disabled'), 'Empty return request was allowed')
  await fillField('.order-return-panel textarea','The item arrived with a damaged handle.')
  await clickButton('Request return')
  check(await evaluate('document.body.innerText.includes("Return: Requested")'), 'Customer return request was not shown')
  await clickButton('Seller view')
  await fillField('.order-return-panel textarea','Return all items to 10 Test Road, Colombo.')
  await clickButton('Approve return')
  await clickButton('Customer view')
  await fillField('.order-return-panel input','Test Return Courier')
  await fillField('.order-return-panel label:last-of-type input','RETURN-UI-123')
  await clickButton('Confirm return parcel sent')
  check(await evaluate('document.body.innerText.includes("RETURN-UI-123")'), 'Return parcel tracking was not displayed')
  await clickButton('Seller view')
  await clickButton('Confirm return received')
  check(await evaluate('document.body.innerText.includes("Refund: Pending")'), 'Received return did not show pending refund')
  await fillField('.order-return-panel input','BANK-REFUND-UI')
  await clickButton('Record completed bank refund')
  check(await evaluate('document.body.innerText.includes("Refund: Refunded")&&document.body.innerText.includes("BANK-REFUND-UI")'), 'Manual bank refund was not recorded')
  check(await evaluate('document.querySelectorAll(".entrepreneur-customer").length===2&&document.querySelector(".entrepreneur-customer summary").innerText.includes("2 orders")'), 'Shop customer grouping failed')
  await evaluate('document.querySelector(".entrepreneur-customer").open=true')
  check(await evaluate('document.querySelector(".entrepreneur-customer").innerText.includes("SECOND-PURCHASE")'), 'Admin customer purchase details missing')
  await fillField('.entrepreneur-customers input','Guest buyer')
  check(await evaluate('document.querySelectorAll(".entrepreneur-customer").length===1&&document.querySelector(".entrepreneur-customer summary").innerText.includes("Guest buyer")'), 'Admin customer search failed')
  check(await evaluate('document.documentElement.scrollWidth<=innerWidth&&parseFloat(getComputedStyle(document.querySelector(".entrepreneur-customers input")).fontSize)>=16'), 'Return UI mobile visibility failed')
  const returnScreenshot=await send('Page.captureScreenshot',{format:'png'})
  await writeFile('private/review/customer-return-mobile.png',Buffer.from(returnScreenshot.data,'base64'))
  check(errors.length === 0, `Browser runtime errors: ${errors.join('; ')}`)
  console.log('PASS: Dark-blue customer theme, dashboard, categories/prices, favourites, address book, purchased-item history/filters, customer reviews/admin moderation, receipts and independent shop-order flow. Return request/approval/shipment/receipt/refund and admin customer profiles. No browser runtime errors.')
} finally {
  try { await send('Browser.close') } catch {}
  if (browser.exitCode === null) browser.kill()
  await pause(300)
  const resolved = path.resolve(profile), temporaryRoot = path.resolve(tmpdir()) + path.sep
  if (!resolved.startsWith(temporaryRoot) || !path.basename(resolved).startsWith('camy-browser-smoke-')) throw Error('Unexpected browser profile cleanup path')
  await rm(resolved, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
}
