<?php
declare(strict_types=1);
require __DIR__.'/../api/config.php';
require __DIR__.'/../api/security.php';
session_save_path(__DIR__.'/../private/sessions');
if(!is_dir(session_save_path()))mkdir(session_save_path(),0700,true);
session_start();
function valid_password(string $password): void {
    if(strlen($password)<8 || !preg_match('/[A-Za-z]/',$password) || !preg_match('/\d/',$password))response(['message'=>'Invalid password'],422);
}
final class ApiResult extends RuntimeException { public function __construct(public array $data, public int $status){parent::__construct('API result');} }
function response(array $data,int $status=200): never {throw new ApiResult($data,$status);}
function input(): array {return $GLOBALS['payload'] ?? [];}
function current_user(PDO $pdo): ?array {return $GLOBALS['actor'] ?? null;}
function require_admin(PDO $pdo): array {$user=current_user($pdo);if(!$user||!in_array($user['role'],['admin','manager'],true))response(['message'=>'Forbidden'],403);return $user;}
require __DIR__.'/../api/marketplace.php';
require __DIR__.'/../api/profiles.php';
function endpoint(PDO $pdo,string $path,string $method,array $data=[],int $expected=200): array {
    $GLOBALS['payload']=$data;try{market_route($pdo,$path,$method);throw new RuntimeException('No API response');}catch(ApiResult $r){if($pdo->inTransaction())$pdo->rollBack();if($r->status!==$expected)throw new RuntimeException($path.' returned '.$r->status.': '.json_encode($r->data));return $r->data;}
}
$pdo=new PDO('mysql:host='.DB_HOST.';port='.DB_PORT.';charset=utf8mb4',DB_USER,DB_PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$name='camy_workflow_test_'.bin2hex(random_bytes(5));$receiptFiles=[];
try{
    $pdo->exec("CREATE DATABASE `$name`");$pdo->exec("USE `$name`");$pdo->exec(file_get_contents(__DIR__.'/../database/schema.sql'));
    $pdo->exec("INSERT INTO users(id,member_id,full_name,email,password_hash,role,status) VALUES(1,'CE-TEST','Test seller','test@example.com','unused','entrepreneur','active')");
    $state=['products'=>[['id'=>1,'code'=>'TEST','name'=>'Test product','category'=>'Test','description'=>'Test','price'=>100,'stock'=>10]],'entrepreneurs'=>[['id'=>'CE-TEST','name'=>'Test seller','city'=>'Colombo']],'tiers'=>[],'requests'=>[],'inventory'=>[],'orders'=>[],'catalogue_live'=>true,'catalogue_seeded'=>true];
    $pdo->exec("INSERT INTO marketplace_state(id,state_json) VALUES(1,'{}')");market_save($pdo,$state);
    $bank=['bank'=>'Test bank','branch'=>'Test branch','holder'=>'Test holder','account'=>'000001'];
    $admin=['id'=>2,'role'=>'admin','member_id'=>null];$seller=['id'=>1,'role'=>'entrepreneur','member_id'=>'CE-TEST','full_name'=>'Test seller'];
    $GLOBALS['actor']=$admin;endpoint($pdo,'/marketplace/bank','POST',$bank);
    $GLOBALS['actor']=$seller;endpoint($pdo,'/marketplace/bank','POST',$bank);
    $request=endpoint($pdo,'/marketplace/requests','POST',['items'=>[['productId'=>1,'qty'=>4]]],201)['request'];$id=$request['id'];
    endpoint($pdo,"/marketplace/requests/$id/edit",'POST',['items'=>[['productId'=>1,'qty'=>4,'price'=>90]]],403);
    $GLOBALS['actor']=$admin;
    endpoint($pdo,"/marketplace/requests/$id/edit",'POST',['items'=>[['productId'=>1,'qty'=>0,'price'=>90]]],422);
    $edited=endpoint($pdo,"/marketplace/requests/$id/edit",'POST',['items'=>[['productId'=>1,'qty'=>4,'price'=>90]]]);
    if((float)$edited['state']['requests'][0]['total']!==360.0)throw new RuntimeException('Edited total was not recalculated.');
    endpoint($pdo,"/marketplace/requests/$id/edit",'POST',['items'=>[['productId'=>1,'qty'=>4,'price'=>100]]]);
    $GLOBALS['actor']=$seller;
    $receipt=['reference'=>'TEST-PAYMENT','receipt'=>'data:application/pdf;base64,'.base64_encode("%PDF-1.4\nTest receipt"),'receiptName'=>'test.pdf'];
    endpoint($pdo,"/marketplace/requests/$id/receipt",'POST',$receipt,409);
    $GLOBALS['actor']=$admin;endpoint($pdo,"/marketplace/requests/$id/dispatch",'POST',[],409);endpoint($pdo,"/marketplace/requests/$id/approve",'POST');endpoint($pdo,"/marketplace/requests/$id/dispatch",'POST',[],409);
    $GLOBALS['actor']=$seller;endpoint($pdo,"/marketplace/requests/$id/receipt",'POST',$receipt);
    $GLOBALS['actor']=$admin;endpoint($pdo,"/marketplace/requests/$id/retry",'POST',['reason'=>'Wrong reference']);
    $GLOBALS['actor']=$seller;endpoint($pdo,"/marketplace/requests/$id/receipt",'POST',$receipt);
    $GLOBALS['actor']=$admin;endpoint($pdo,"/marketplace/requests/$id/verify",'POST');endpoint($pdo,"/marketplace/requests/$id/dispatch",'POST');endpoint($pdo,"/marketplace/requests/$id/dispatch",'POST',[],409);
    $GLOBALS['actor']=null;
    $buyer=['name'=>'Test buyer','phone'=>'0771234567','district'=>'Colombo','address'=>'123 Test street'];
    endpoint($pdo,'/marketplace/orders','POST',[],401);
    endpoint($pdo,'/customer/register','POST',$buyer+['email'=>'buyer@example.com','password'=>'Buyer1234'],201);
    endpoint($pdo,'/customer/register','POST',$buyer+['email'=>'buyer@example.com','password'=>'Buyer1234'],409);
    $order=endpoint($pdo,'/marketplace/orders','POST',['customer'=>$buyer,'items'=>[['shopId'=>'CE-TEST','productId'=>1,'qty'=>2,'expectedPrice'=>100]]],201);$tracking=$order['tracking'][0];$oid=$tracking['id'];
    if(endpoint($pdo,'/customer/orders','GET')['tracking'][0]['id']!==$oid)throw new RuntimeException('Customer order is not saved to account.');
    endpoint($pdo,'/customer/logout','POST');
    endpoint($pdo,'/customer/orders','GET',[],401);
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'wrong'],401);
    endpoint($pdo,'/customer/register','POST',$buyer+['email'=>'other@example.com','password'=>'Buyer1234'],201);
    if(endpoint($pdo,'/customer/orders','GET')['tracking'])throw new RuntimeException('Another customer can see buyer orders.');
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'Buyer1234']);
    $saved=endpoint($pdo,'/customer/me','GET')['customer'];
    if($saved['address']!==$buyer['address']||$saved['phone']!==$buyer['phone'])throw new RuntimeException('Delivery details were not saved.');
    endpoint($pdo,'/customer/favourites','POST',['shopId'=>'CE-TEST','productId'=>1,'saved'=>true]);
    endpoint($pdo,'/customer/favourites','POST',['shopId'=>'CE-TEST','productId'=>1,'saved'=>true]);
    if(count(endpoint($pdo,'/customer/favourites','GET')['favourites'])!==1)throw new RuntimeException('Saved products duplicated.');
    endpoint($pdo,'/customer/addresses','POST',$buyer+['label'=>'Home']);
    $address=endpoint($pdo,'/customer/addresses','GET')['addresses'][0];
    endpoint($pdo,'/customer/login','POST',['email'=>'other@example.com','password'=>'Buyer1234']);
    if(endpoint($pdo,'/customer/favourites','GET')['favourites']||endpoint($pdo,'/customer/addresses','GET')['addresses'])throw new RuntimeException('Customer account features leaked between accounts.');
    endpoint($pdo,'/customer/addresses','POST',$buyer+['id'=>$address['id'],'label'=>'Other'],404);
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'Buyer1234']);
    endpoint($pdo,'/customer/addresses','POST',['id'=>$address['id'],'label'=>'Office','name'=>$buyer['name'],'phone'=>$buyer['phone'],'district'=>'Colombo','address'=>'456 Office Street']);
    if(endpoint($pdo,'/customer/addresses','GET')['addresses'][0]['label']!=='Office')throw new RuntimeException('Address edit did not persist.');
    endpoint($pdo,'/customer/reviews','POST',['orderId'=>$oid,'productId'=>1,'rating'=>5,'comment'=>'Good product'],403);
    endpoint($pdo,"/marketplace/orders/$oid/tracking",'GET',[],401);$_GET['token']=$tracking['token'];endpoint($pdo,"/marketplace/orders/$oid/tracking",'GET');$_GET=[];
    $GLOBALS['actor']=['id'=>3,'role'=>'entrepreneur','member_id'=>'CE-OTHER'];endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Awaiting payment'],403);
    $GLOBALS['actor']=$seller;endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Dispatched'],409);endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Awaiting payment']);
    if(endpoint($pdo,'/customer/orders','GET')['tracking'][0]['status']!=='Awaiting payment')throw new RuntimeException('Shop approval missing from customer account.');
    $GLOBALS['actor']=null;endpoint($pdo,"/marketplace/orders/$oid/receipt",'POST',$receipt+['token'=>$tracking['token']]);
    $GLOBALS['actor']=$seller;endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Processing']);
    endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Dispatched'],422);
    endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Dispatched','trackingNumber'=>str_repeat('X',121)],422);
    endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Dispatched','courier'=>'Test Courier','trackingNumber'=>'TRACK-123456']);
    $_GET['token']=$tracking['token'];$parcel=endpoint($pdo,"/marketplace/orders/$oid/tracking",'GET')['order'];$_GET=[];
    if($parcel['trackingNumber']!=='TRACK-123456'||$parcel['courier']!=='Test Courier')throw new RuntimeException('Customer cannot see dispatch tracking.');
    endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Delivered']);
    endpoint($pdo,'/customer/reviews','POST',['orderId'=>$oid,'productId'=>1,'rating'=>6,'comment'=>'Good product'],422);
    endpoint($pdo,'/customer/reviews','POST',['orderId'=>$oid,'productId'=>999,'rating'=>5,'comment'=>'Good product'],403);
    endpoint($pdo,'/customer/login','POST',['email'=>'other@example.com','password'=>'Buyer1234']);
    endpoint($pdo,'/customer/reviews','POST',['orderId'=>$oid,'productId'=>1,'rating'=>5,'comment'=>'Good product'],403);
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'Buyer1234']);
    endpoint($pdo,'/customer/reviews','POST',['orderId'=>$oid,'productId'=>1,'rating'=>5,'comment'=>'Good product, safely delivered.']);
    $review=endpoint($pdo,'/customer/reviews','GET')['reviews'][0];
    $_GET=['shopId'=>'CE-TEST','productId'=>'1'];
    if(endpoint($pdo,'/marketplace/reviews','GET')['reviews'])throw new RuntimeException('Unmoderated feedback was published.');
    endpoint($pdo,'/admin/customer-reviews','GET',[],403);
    $GLOBALS['actor']=$admin;endpoint($pdo,'/admin/customer-reviews','POST',['id'=>$review['id'],'status'=>'Published','reply'=>'Thank you for your feedback.']);
    $published=endpoint($pdo,'/marketplace/reviews','GET')['reviews'][0];
    if($published['rating']!==5||$published['admin_reply']!=='Thank you for your feedback.'||isset($published['customer_email']))throw new RuntimeException('Published review or customer privacy is incorrect.');
    $summary=endpoint($pdo,'/marketplace/public','GET')['ratingSummary'][0];if((int)$summary['count']!==1||(float)$summary['average']!==5.0)throw new RuntimeException('Catalogue rating summary is incorrect.');
    $GLOBALS['actor']=$seller;endpoint($pdo,'/customer/reviews','POST',['orderId'=>$oid,'productId'=>1,'rating'=>4,'comment'=>'Updated feedback after using the product.']);
    if(endpoint($pdo,'/marketplace/reviews','GET')['reviews']||count(endpoint($pdo,'/customer/reviews','GET')['reviews'])!==1)throw new RuntimeException('Edited feedback was not re-moderated or duplicated.');$_GET=[];
    endpoint($pdo,"/marketplace/orders/$oid/return/ship",'POST',['trackingNumber'=>'RET-1','courier'=>'Courier'],409);
    endpoint($pdo,"/marketplace/orders/$oid/return/request",'POST',['reason'=>'Bad'],422);
    endpoint($pdo,'/customer/login','POST',['email'=>'other@example.com','password'=>'Buyer1234']);
    endpoint($pdo,"/marketplace/orders/$oid/return/request",'POST',['reason'=>'The product arrived damaged.'],403);
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'Buyer1234']);
    endpoint($pdo,"/marketplace/orders/$oid/return/request",'POST',['reason'=>'The product arrived damaged.']);
    endpoint($pdo,"/marketplace/orders/$oid/return/request",'POST',['reason'=>'Duplicate return request.'],409);
    if(!profile_has_obligations(market_state($pdo),'CE-TEST'))throw new RuntimeException('An open return must prevent shop closure.');
    endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Returned'],409);
    endpoint($pdo,"/marketplace/orders/$oid/return/receive",'POST',[],409);
    endpoint($pdo,"/marketplace/orders/$oid/return/approve",'POST',['instructions'=>''],422);
    $wrongSeller=['id'=>99,'role'=>'entrepreneur','member_id'=>'OTHER-SHOP'];$GLOBALS['actor']=$wrongSeller;
    endpoint($pdo,"/marketplace/orders/$oid/return/approve",'POST',['instructions'=>'Return to the shop address.'],403);
    $GLOBALS['actor']=$seller;
    endpoint($pdo,"/marketplace/orders/$oid/return/approve",'POST',['instructions'=>'Return all items to 10 Test Road, Colombo.']);
    if(market_state($pdo)['inventory'][0]['qty']!==2)throw new RuntimeException('Approval restored return stock too early.');
    endpoint($pdo,'/customer/login','POST',['email'=>'other@example.com','password'=>'Buyer1234']);
    endpoint($pdo,"/marketplace/orders/$oid/return/ship",'POST',['trackingNumber'=>'RET-1','courier'=>'Test Courier'],403);
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'Buyer1234']);
    endpoint($pdo,"/marketplace/orders/$oid/return/ship",'POST',['trackingNumber'=>'RET-1','courier'=>'Test Courier']);
    $returnHistory=endpoint($pdo,'/customer/orders','GET')['tracking'][0];if(($returnHistory['return']['status']??'')!=='Shipped')throw new RuntimeException('Return status missing from purchase history.');
    $returned=endpoint($pdo,"/marketplace/orders/$oid/return/receive",'POST')['order'];
    if($returned['status']!=='Returned'||$returned['return']['refundStatus']!=='Pending')throw new RuntimeException('Return receipt did not update refund workflow.');
    endpoint($pdo,"/marketplace/orders/$oid/return/receive",'POST',[],409);
    if(!profile_has_obligations(market_state($pdo),'CE-TEST'))throw new RuntimeException('An outstanding refund must prevent shop closure.');
    endpoint($pdo,"/marketplace/orders/$oid/return/refund",'POST',['reference'=>'BANK-REFUND-123']);
    endpoint($pdo,"/marketplace/orders/$oid/return/refund",'POST',['reference'=>'BANK-REFUND-123'],409);
    endpoint($pdo,"/marketplace/orders/$oid/status",'POST',['status'=>'Returned'],409);
    $state=market_state($pdo);if($state['products'][0]['stock']!==6||$state['inventory'][0]['qty']!==4)throw new RuntimeException('Stock must be transferred once and restored once.');
    // Two shops sharing a product still require independent prices, approvals and bank payments.
    $pdo->exec("INSERT INTO users(id,member_id,full_name,email,password_hash,role,status) VALUES(4,'CE-SECOND','Second seller','second@example.com','unused','entrepreneur','active')");
    $state['inventory'][]=['entrepreneurId'=>'CE-SECOND','productId'=>1,'qty'=>3,'price'=>150];market_save($pdo,$state);
    $second=['id'=>4,'role'=>'entrepreneur','member_id'=>'CE-SECOND','full_name'=>'Second seller'];
    $GLOBALS['actor']=$second;endpoint($pdo,'/marketplace/bank','POST',['bank'=>'Second bank','branch'=>'Second branch','holder'=>'Second holder','account'=>'000002']);
    $GLOBALS['actor']=null;
    $mixed=['requestKey'=>'mixed-checkout-test-001','customer'=>$buyer,'items'=>[['shopId'=>'CE-TEST','productId'=>1,'qty'=>1,'expectedPrice'=>100],['shopId'=>'CE-SECOND','productId'=>1,'qty'=>2,'expectedPrice'=>150]]];
    $count=count(market_state($pdo)['orders']);
    $bad=$mixed;$bad['items'][1]['qty']=99;endpoint($pdo,'/marketplace/orders','POST',$bad,409);
    if(count(market_state($pdo)['orders'])!==$count)throw new RuntimeException('Failed mixed cart created a partial order.');
    $split=endpoint($pdo,'/marketplace/orders','POST',$mixed,201);$splitTracking=$split['tracking'];
    if(count($split['ids'])!==2)throw new RuntimeException('Mixed checkout did not create two shop orders.');
    $retry=endpoint($pdo,'/marketplace/orders','POST',$mixed,201);
    if($retry['ids']!==$split['ids']||count(market_state($pdo)['orders'])!==$count+2)throw new RuntimeException('Checkout retry duplicated orders.');
    $changed=$mixed;$changed['items'][0]['qty']=2;endpoint($pdo,'/marketplace/orders','POST',$changed,409);
    $firstId=$splitTracking[0]['id'];$secondId=$splitTracking[1]['id'];
    $GLOBALS['actor']=$seller;endpoint($pdo,"/marketplace/orders/$firstId/status",'POST',['status'=>'Awaiting payment']);
    $GLOBALS['actor']=$second;endpoint($pdo,"/marketplace/orders/$secondId/status",'POST',['status'=>'Awaiting payment']);
    $_GET['token']=$splitTracking[0]['token'];$firstOrder=endpoint($pdo,"/marketplace/orders/$firstId/tracking",'GET')['order'];
    $_GET['token']=$splitTracking[1]['token'];$secondOrder=endpoint($pdo,"/marketplace/orders/$secondId/tracking",'GET')['order'];$_GET=[];
    if($firstOrder['bankDetails']['account']!=='000001'||$secondOrder['bankDetails']['account']!=='000002'||$firstOrder['amount']!=100||$secondOrder['amount']!=300)throw new RuntimeException('Shop bank details or amounts crossed between orders.');
    $GLOBALS['actor']=null;endpoint($pdo,"/marketplace/orders/$secondId/receipt",'POST',$receipt+['token'=>$splitTracking[0]['token']],401);
    endpoint($pdo,"/marketplace/orders/$secondId/receipt",'POST',$receipt+['token'=>$splitTracking[1]['token']]);
    $GLOBALS['actor']=$seller;endpoint($pdo,"/marketplace/orders/$firstId/status",'POST',['status'=>'Rejected']);
    $_GET['token']=$splitTracking[1]['token'];$unaffected=endpoint($pdo,"/marketplace/orders/$secondId/tracking",'GET')['order'];$_GET=[];
    if($unaffected['status']!=='Payment review')throw new RuntimeException('Rejecting one shop changed the other shop order.');
    $GLOBALS['actor']=$second;endpoint($pdo,"/marketplace/orders/$secondId/status",'POST',['status'=>'Processing']);
    endpoint($pdo,'/customer/password','POST',['currentPassword'=>'wrong','newPassword'=>'NewBuyer1234'],422);
    $oldVersion=$_SESSION['customer_version'];endpoint($pdo,'/customer/password','POST',['currentPassword'=>'Buyer1234','newPassword'=>'NewBuyer1234']);
    $_SESSION['customer_version']=$oldVersion;if(endpoint($pdo,'/customer/me','GET')['customer']!==null)throw new RuntimeException('Password change did not revoke old sessions.');
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'Buyer1234'],401);
    endpoint($pdo,'/customer/login','POST',['email'=>'buyer@example.com','password'=>'NewBuyer1234']);
    $preview=endpoint($pdo,'/marketplace/preview','GET');if(empty($preview['preview'])||!$preview['products'])throw new RuntimeException('Removable preview collection is empty.');
    session_destroy();
    echo "API integration passed: customer return ownership/transitions/tracking/refunds/stock restored once, purchase history, favourites, address ownership, verified-buyer feedback/moderation/privacy, password session revocation, removable previews and independent shop-order payments.\n";
}finally{
    if($pdo->inTransaction())$pdo->rollBack();
    if(isset($state))foreach($state['requests'] ?? [] as $row)if(isset($row['id']))foreach(glob(__DIR__.'/../private/receipts/'.$row['id'].'-*') ?: [] as $file)unlink($file);
    if(isset($oid))foreach(glob(__DIR__.'/../private/receipts/'.$oid.'-*') ?: [] as $file)unlink($file);
    if(isset($id))foreach(glob(__DIR__.'/../private/receipts/'.$id.'-*') ?: [] as $file)unlink($file);
    if(isset($splitTracking))foreach($splitTracking as $item)foreach(glob(__DIR__.'/../private/receipts/'.$item['id'].'-*') ?: [] as $file)unlink($file);
    $pdo->exec("DROP DATABASE `$name`");
}
