import { useEffect, useState } from 'react'
import { ArrowRight, Heart, MapPin, PackageOpen, Receipt, Search, ShieldCheck, Star, Truck } from 'lucide-react'
import { api } from './api'
import { CustomerTracker } from './Workflow'
import { Stars } from './ProductReviews'

const money = value => `Rs. ${Number(value || 0).toLocaleString('en-LK')}`
export const accountTabs = [['account','Overview'],['orders','My orders'],['history','Purchase history'],['saved','Saved products'],['reviews','My feedback'],['addresses','Address book']]

export function CustomerOverview({ account, orders, favourites, reviews, onTab, editAccount }) {
  const delivered = orders.filter(order => order.status === 'Delivered')
  const metrics = [[PackageOpen,'Orders',orders.length,'orders'],[Receipt,'Ready to pay',orders.filter(order => order.status === 'Awaiting payment').length,'orders'],[Heart,'Saved products',favourites.length,'saved'],[Star,'My feedback',reviews.length,'reviews']]
  return <section className="customer-overview"><div className="account-welcome"><span className="shop-eyebrow">YOUR CAMY ACCOUNT</span><h1>Hello, {account.name.split(' ')[0]}.</h1><p>Everything you need, from your first request to your next delivery.</p><span><ShieldCheck size={17}/>Bank transfer & receipt upload · No online card payments</span></div><div className="account-metrics">{metrics.map(([Icon,label,value,tab]) => <button key={label} onClick={() => onTab(tab)}><Icon/><strong>{value}</strong><span>{label}</span><ArrowRight size={17}/></button>)}</div><div className="account-overview-grid"><section className="account-panel"><header><h2>Recent purchases</h2><button onClick={() => onTab('history')}>View all <ArrowRight size={16}/></button></header>{orders.slice(0,3).map(order => <button className="account-recent-order" key={order.id} onClick={() => onTab('orders')}><img src={order.items?.[0]?.image || '/products/classic-set.png'} alt=""/><span><strong>{order.shop}</strong><small>{order.items?.map(item => `${item.name} × ${item.qty}`).join(', ') || order.id}</small><small>{order.status} · {order.date}</small></span><b>{money(order.amount)}</b></button>)}{!orders.length && <p>Your purchases will appear here when you send an order request.</p>}<div className="account-spend"><span>Delivered purchases</span><strong>{money(delivered.reduce((sum,order) => sum + Number(order.amount),0))}</strong></div></section><section className="account-panel"><header><h2>Default delivery address</h2><button onClick={editAccount}>Edit</button></header><div className="account-address"><MapPin/><strong>{account.name}</strong><p>{account.address}<br/>{account.district}</p><span>{account.phone}</span></div><button className="shop-secondary" onClick={() => onTab('addresses')}>Manage delivery addresses <ArrowRight size={16}/></button></section></div><div className="account-how"><Truck/><span><strong>A clear path to your doorstep</strong><p>Request → shop approval → bank transfer → upload receipt → payment verification → dispatch & tracking → delivery.</p></span></div></section>
}

export function CustomerPurchaseHistory({ orders, history, reviews, onReview, reorder, onOrderUpdate }) {
  const [search,setSearch]=useState('')
  const [status,setStatus]=useState('All')
  const [category,setCategory]=useState('All')
  const [shop,setShop]=useState('All')
  const [from,setFrom]=useState('')
  const [to,setTo]=useState('')
  const [sort,setSort]=useState('newest')
  const categories=[...new Set(orders.flatMap(order=>(order.items || []).map(item=>item.category || 'Other')))]
  const shops=[...new Set(orders.map(order=>order.shop))]
  const visible=orders.filter(order=>(status==='All'||(status==='Return requests'?!!order.return:order.status===status))&&(shop==='All'||order.shop===shop)&&(category==='All'||order.items?.some(item=>(item.category || 'Other')===category))&&(!from||order.date>=from)&&(!to||order.date<=to)&&`${order.id} ${order.shop} ${order.items?.map(item=>item.name).join(' ') || ''}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='amount' ? b.amount-a.amount : sort==='oldest' ? (a.createdAt || a.date).localeCompare(b.createdAt || b.date) : (b.createdAt || b.date).localeCompare(a.createdAt || a.date))
  const clear=()=>{setSearch('');setStatus('All');setCategory('All');setShop('All');setFrom('');setTo('');setSort('newest')}
  return <><div className="account-order-filters"><label className="shop-search"><Search size={18}/><input aria-label="Search purchases" placeholder="Search order number, product or shop" value={search} onChange={event=>setSearch(event.target.value)}/></label><div className="account-filter-grid"><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}>{['All','Pending','Awaiting payment','Payment review','Processing','Dispatched','Delivered','Rejected','Returned','Return requests'].map(item=><option key={item} value={item}>{item==='Processing'?'Payment verified':item}</option>)}</select></label><label>Category<select value={category} onChange={event=>setCategory(event.target.value)}><option>All</option>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Shop<select value={shop} onChange={event=>setShop(event.target.value)}><option>All</option>{shops.map(item=><option key={item}>{item}</option>)}</select></label><label>From<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To<input type="date" min={from || undefined} value={to} onChange={event=>setTo(event.target.value)}/></label><label>Sort<select value={sort} onChange={event=>setSort(event.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="amount">Highest value</option></select></label></div><footer><span>{visible.length} of {orders.length} {history?'purchases':'orders'} · {money(visible.reduce((sum,order)=>sum+Number(order.amount),0))}</span><button className="shop-secondary" onClick={clear}>Clear filters</button></footer></div>{visible.map(order=><section key={order.id} className="account-purchase"><div className="account-purchase-images">{(order.items || []).map(item=><div key={item.id || item.productId}><img src={item.image || '/products/classic-set.png'} alt={item.name}/><span><strong>{item.name}</strong><small>{item.category} · Qty {item.qty} · {money(item.price)}</small></span></div>)}{history && <button className="shop-secondary" onClick={()=>reorder(order)}>Buy again</button>}</div><CustomerTracker tracking={order} canReview reviews={reviews} onReview={onReview} onOrderUpdate={onOrderUpdate}/></section>)}{!visible.length && <div className="shop-empty"><PackageOpen/><h2>No matching purchases</h2><p>Change your filters to find a previous order.</p><button className="shop-secondary" onClick={clear}>Reset filters</button></div>}</>
}

export function CustomerFeedback({ reviews, onOrders }) {
  return <section className="account-panel"><h2>My product feedback</h2><p>Your ratings, comments, moderation status and CAMY replies.</p>{reviews.map(review=><article className="account-feedback" key={review.id}><header><strong>{review.product_name}</strong><span className="review-state">{review.status}</span></header><Stars rating={review.rating}/><p>{review.comment}</p>{review.admin_reply && <blockquote><b>CAMY response</b><p>{review.admin_reply}</p></blockquote>}<small>Order {review.order_id} · {review.updated_at}</small></article>)}{!reviews.length && <p>No feedback yet. Rate products after your order is delivered.</p>}<button className="shop-primary" onClick={onOrders}>Review a delivered purchase <ArrowRight size={17}/></button></section>
}

export function CustomerAddressBook({ account, addresses, districts, onReload, onAccount, useAddress }) {
  const [draft,setDraft]=useState(null)
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const [message,setMessage]=useState('')
  const mutate=async data=>{setBusy(true);setError('');try{await api('/customer/addresses',{method:'POST',body:JSON.stringify(data)});await onReload();setDraft(null);setMessage('Address book updated.')}catch(error){setError(error.message)}finally{setBusy(false)}}
  const makeDefault=async address=>{setBusy(true);setError('');try{const result=await api('/customer/profile',{method:'POST',body:JSON.stringify(address)});onAccount(result.customer);setMessage('Default delivery address updated.')}catch(error){setError(error.message)}finally{setBusy(false)}}
  return <section className="account-panel"><header><h2>Delivery address book</h2><button className="shop-secondary" disabled={busy} onClick={()=>{setDraft({label:'Home',name:account.name,phone:account.phone,district:account.district,address:account.address});setMessage('')}}>Add address</button></header><p>Save up to 10 addresses. Select one at checkout.</p>{error && <p className="shop-alert" role="alert">{error}</p>}{message && <p className="shop-success" role="status">{message}</p>}<div className="address-book-grid"><article><span className="review-state">Default address</span><h3>{account.name}</h3><p>{account.address}<br/>{account.district}</p><small>{account.phone}</small><button className="shop-secondary" disabled={busy} onClick={()=>useAddress(account)}>Use for checkout</button></article>{addresses.map(address=><article key={address.id}><span className="review-state">{address.label}</span><h3>{address.name}</h3><p>{address.address}<br/>{address.district}</p><small>{address.phone}</small><div><button disabled={busy} onClick={()=>setDraft({...address})}>Edit</button><button disabled={busy} onClick={()=>makeDefault(address)}>Make default</button><button disabled={busy} onClick={()=>mutate({id:address.id,action:'delete'})}>Remove</button></div><button className="shop-secondary" disabled={busy} onClick={()=>useAddress(address)}>Use for checkout</button></article>)}</div>{draft && <form className="shop-checkout address-editor" onSubmit={event=>{event.preventDefault();mutate(draft)}}><fieldset disabled={busy}><h3>{draft.id?'Edit address':'New address'}</h3>{[['label','Address label',''],['name','Full name','name'],['phone','Mobile number','tel']].map(([key,label,autoComplete])=><label key={key}>{label}<input required maxLength={key==='label'?60:key==='name'?150:30} autoComplete={autoComplete || undefined} value={draft[key]} onChange={event=>setDraft(old=>({...old,[key]:event.target.value}))}/></label>)}<label>District<select required value={draft.district} onChange={event=>setDraft(old=>({...old,district:event.target.value}))}><option value="">Choose district</option>{districts.map(item=><option key={item}>{item}</option>)}</select></label><label>Delivery address<textarea required minLength={8} maxLength={2000} autoComplete="street-address" value={draft.address} onChange={event=>setDraft(old=>({...old,address:event.target.value}))}/></label><button className="shop-primary">{busy?'Saving…':'Save address'}</button><button type="button" className="shop-secondary" onClick={()=>setDraft(null)}>Cancel</button></fieldset></form>}</section>
}
